# Generated by Django 5.1.15 on 2026-05-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobility", "0003_taskmessage_taskincidentreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("matched", "Matched"),
                    ("in_transit", "In transit"),
                    ("delivered", "Delivered"),
                    ("damaged", "Damaged"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="open",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="emergencyalert",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("acknowledged", "Acknowledged"),
                    ("resolved", "Resolved"),
                ],
                db_index=True,
                default="open",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="riderequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("matched", "Matched"),
                    ("picked_up", "Picked up"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="open",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="trackingsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("live", "Live"),
                    ("paused", "Paused"),
                    ("ended", "Ended"),
                ],
                db_index=True,
                default="idle",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="travelmatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("proposed", "Proposed"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="proposed",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="travelplan",
            name="departure_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="travelplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=16,
            ),
        ),
    ]
