# Railway Configuration for Monorepo
# This tells Railway to deploy only the backend service
# https://docs.railway.app/guides/monorepo

[[services]]
name = "backend"

[services.build]
dockerfile = "backend/Dockerfile"
context = "backend"