# Railway Configuration for Monorepo
# Explicitly skip Railpack and use Dockerfile directly
# https://docs.railway.app/guides/monorepo

[[services]]
name = "backend"
builder = "dockerfile"

[services.build]
dockerfile = "backend/Dockerfile"
context = "backend"