org.gradle.workers.max=4
org.gradle.parallel=false
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -XX:ActiveProcessorCount=8
android.useAndroidX=true
android.enableJetifier=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
rive.ndk.version=29.0.13846066
android.ndk.suppressMinSdkVersionError=21
