"""Add paystack fields to payments table

Revision ID: d9f50014a847
Revises: 
Create Date: 2025-10-21 12:05:52.203963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f50014a847'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('paystack_reference', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('paystack_access_code', sa.String(), nullable=True))
    op.drop_index('ix_payments_monnify_reference', table_name='payments')
    op.create_index(op.f('ix_payments_paystack_reference'), 'payments', ['paystack_reference'], unique=False)
    op.drop_column('payments', 'monnify_payment_reference')
    op.drop_column('payments', 'monnify_reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('monnify_reference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('monnify_payment_reference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payments_paystack_reference'), table_name='payments')
    op.create_index('ix_payments_monnify_reference', 'payments', ['monnify_reference'], unique=False)
    op.drop_column('payments', 'paystack_access_code')
    op.drop_column('payments', 'paystack_reference')
    # ### end Alembic commands ###
