"""Make phone, first_name, last_name optional in users table

Revision ID: make_optional_001
Revises: d9f50014a847
Create Date: 2025-10-22 22:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'make_optional_001'
down_revision: Union[str, None] = 'd9f50014a847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make phone nullable
    op.alter_column('users', 'phone',
               existing_type=sa.String(),
               nullable=True)
    # Make first_name nullable
    op.alter_column('users', 'first_name',
               existing_type=sa.String(),
               nullable=True)
    # Make last_name nullable
    op.alter_column('users', 'last_name',
               existing_type=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.String(),
               nullable=False)
    # ### end Alembic commands ###