# Generated by Django 5.1.15 on 2026-05-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_emailverificationcode_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
