# Generated by Django 5.1.15 on 2026-05-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_kycrecord_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationcode",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="emailverificationcode",
            name="code",
            field=models.CharField(max_length=6),
        ),
    ]
