# Generated by Django 5.1.15 on 2026-05-28 20:11

import apps.accounts.encryption
from django.db import migrations


def encrypt_existing_pii(apps, schema_editor):
    KycRecord = apps.get_model("accounts", "KycRecord")
    # After the AlterField above, the historical model already uses
    # EncryptedCharField. Reading bvn/nin runs from_db_value, which returns
    # legacy plaintext as-is (no prefix). Saving runs get_prep_value, which
    # encrypts and prefixes with PII_PREFIX. Idempotent on re-runs because
    # encrypt_pii skips values that already have the prefix.
    for record in KycRecord.objects.all().iterator():
        if record.bvn or record.nin:
            record.save(update_fields=["bvn", "nin", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_emailverificationcode_attempts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycrecord",
            name="bvn",
            field=apps.accounts.encryption.EncryptedCharField(
                blank=True, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="kycrecord",
            name="nin",
            field=apps.accounts.encryption.EncryptedCharField(
                blank=True, max_length=255
            ),
        ),
        migrations.RunPython(
            encrypt_existing_pii, reverse_code=migrations.RunPython.noop
        ),
    ]
