# Generated by Codex on 2026-04-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonnifyReservedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_reference", models.CharField(max_length=64, unique=True)),
                ("reservation_reference", models.CharField(blank=True, max_length=64)),
                ("account_name", models.CharField(max_length=120)),
                ("account_number", models.CharField(blank=True, max_length=20)),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("bank_code", models.CharField(blank=True, max_length=16)),
                ("currency_code", models.CharField(default="NGN", max_length=8)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_name", models.CharField(max_length=120)),
                ("status", models.CharField(blank=True, max_length=24)),
                ("accounts", models.JSONField(blank=True, default=list)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("provider", models.CharField(default="monnify", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monnify_account",
                        to="payments.wallet",
                    ),
                ),
            ],
        ),
    ]
