# Generated by Django 5.1.15 on 2026-05-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_monnifyreservedaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
