name: Deploy Backend to Railway

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Railway
        run: |
          npm install -g @railway/cli
          railway link ${{ secrets.RAILWAY_PROJECT_ID }} --service ${{ secrets.RAILWAY_SERVICE_ID }}
          railway up --service ${{ secrets.RAILWAY_SERVICE_ID }} backend/
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}